'use strict';

/* GoMo VS Planner v3.19.2 — pilotage adaptatif semaine avec plancher quotidien.
   - ne recommande jamais moins de 7,2 M sur un jour VS
   - recalcule la cible moyenne restante apres les scores precedents
   - marge calculee avec la cible ajustee reelle
   - lecture seule : ne modifie ni le moteur VS ni les stocks
*/
(() => {
  const VERSION='3.19.2';
  const DAILY_MIN=7_200_000;
  const UI_KEY='gomo_vs_planner_v316';
  const HIST_KEY='gomo_vs_planner_week_history_v3181';
  let timer=0,observer=null;

  const T={
    fr:{margin:'Marge avec cible ajustée',average:'Cible ajustée',daysLeft:'Jours restants',perDay:'/ jour',ahead:'✅ Tu as de l’avance : vise environ {avg} par jour sur les {days} jours restants, soit {delta} de moins par jour que le mode {mode}.',behind:'⚠️ Pour rester sur la cible semaine, vise environ {avg} par jour sur les {days} jours restants, soit {delta} de plus par jour que le mode {mode}.',steady:'✅ Le rythme est bon : vise environ {avg} par jour sur les {days} jours restants.',floor:'🛡️ Ton avance permettrait une moyenne plus basse, mais le Planner conserve le minimum quotidien de 7,2 M.',todayNeed:'Aujourd’hui, avec {current} déjà enregistré, il reste environ {need} à faire pour atteindre la cible ajustée.',todayOk:'Aujourd’hui, la cible ajustée est déjà atteinte. Le surplus aide les jours suivants.',incomplete:'ℹ️ Complète d’abord les jours passés manquants pour obtenir une cible ajustée fiable.',modeEconomy:'Économie',modeNormal:'Normal',modePush:'Poussée'},
    en:{margin:'Margin with adjusted target',average:'Adjusted target',daysLeft:'Days left',perDay:'/ day',ahead:'✅ You are ahead: aim for about {avg} per day over the {days} remaining days, {delta} less per day than {mode} mode.',behind:'⚠️ To stay on the weekly target, aim for about {avg} per day over the {days} remaining days, {delta} more per day than {mode} mode.',steady:'✅ Your pace is good: aim for about {avg} per day over the {days} remaining days.',floor:'🛡️ Your lead would allow a lower average, but the Planner keeps the 7.2M daily minimum.',todayNeed:'Today, with {current} already recorded, about {need} remains to reach the adjusted target.',todayOk:'Today, the adjusted target is already reached. The surplus helps the following days.',incomplete:'ℹ️ Fill the missing past days first to get a reliable adjusted target.',modeEconomy:'Economy',modeNormal:'Normal',modePush:'Push'},
    de:{margin:'Reserve mit angepasstem Ziel',average:'Angepasstes Ziel',daysLeft:'Verbleibende Tage',perDay:'/ Tag',ahead:'✅ Du liegst vorne: Etwa {avg} pro Tag an den verbleibenden {days} Tagen reichen, also {delta} weniger pro Tag als im Modus {mode}.',behind:'⚠️ Für das Wochenziel brauchst du etwa {avg} pro Tag an den verbleibenden {days} Tagen, also {delta} mehr pro Tag als im Modus {mode}.',steady:'✅ Dein Tempo passt: etwa {avg} pro Tag an den verbleibenden {days} Tagen.',floor:'🛡️ Dein Vorsprung würde weniger erlauben, aber der Planner behält das Tagesminimum von 7,2 Mio.',todayNeed:'Heute sind bereits {current} erfasst; noch etwa {need} bis zum angepassten Ziel.',todayOk:'Das angepasste Tagesziel ist bereits erreicht. Der Überschuss hilft an den nächsten Tagen.',incomplete:'ℹ️ Ergänze zuerst die fehlenden vergangenen Tage.',modeEconomy:'Sparen',modeNormal:'Normal',modePush:'Push'},
    ro:{margin:'Marjă cu țintă ajustată',average:'Țintă ajustată',daysLeft:'Zile rămase',perDay:'/ zi',ahead:'✅ Ești înainte: vizează aproximativ {avg} pe zi în cele {days} zile rămase, cu {delta} mai puțin pe zi decât modul {mode}.',behind:'⚠️ Pentru ținta săptămânală, vizează aproximativ {avg} pe zi în cele {days} zile rămase, cu {delta} mai mult pe zi decât modul {mode}.',steady:'✅ Ritmul este bun: vizează aproximativ {avg} pe zi în cele {days} zile rămase.',floor:'🛡️ Avansul ar permite o medie mai mică, dar Planner păstrează minimul zilnic de 7,2 M.',todayNeed:'Astăzi ai deja {current}; mai sunt aproximativ {need} pentru ținta ajustată.',todayOk:'Ținta ajustată de azi este deja atinsă.',incomplete:'ℹ️ Completează mai întâi zilele trecute lipsă.',modeEconomy:'Economie',modeNormal:'Normal',modePush:'Forțare'},
    uk:{margin:'Запас зі скоригованою ціллю',average:'Скоригована ціль',daysLeft:'Днів залишилось',perDay:'/ день',ahead:'✅ Є запас: можна цілитись приблизно в {avg} на день протягом {days} днів, на {delta} менше за режим {mode}.',behind:'⚠️ Для тижневої цілі потрібно приблизно {avg} на день протягом {days} днів, на {delta} більше за режим {mode}.',steady:'✅ Темп добрий: приблизно {avg} на день протягом {days} днів.',floor:'🛡️ Запас дозволив би менше, але Planner зберігає щоденний мінімум 7,2 M.',todayNeed:'Сьогодні вже записано {current}; до скоригованої цілі лишається приблизно {need}.',todayOk:'Скориговану ціль на сьогодні вже досягнуто.',incomplete:'ℹ️ Спочатку заповни пропущені минулі дні.',modeEconomy:'Економія',modeNormal:'Звичайний',modePush:'Ривок'},
    ko:{margin:'조정 목표 여유',average:'조정 목표',daysLeft:'남은 일수',perDay:'/ 일',ahead:'✅ 여유가 있습니다: 남은 {days}일 동안 하루 약 {avg}를 목표로 하면 되며 {mode} 모드보다 하루 {delta} 적습니다.',behind:'⚠️ 주간 목표를 위해 남은 {days}일 동안 하루 약 {avg}가 필요하며 {mode} 모드보다 하루 {delta} 많습니다.',steady:'✅ 현재 속도가 좋습니다: 남은 {days}일 동안 하루 약 {avg}를 목표로 하세요.',floor:'🛡️ 더 낮게 잡을 수 있지만 Planner는 하루 최소 7.2M을 유지합니다.',todayNeed:'오늘 이미 {current}가 기록되어 있으며 조정 목표까지 약 {need} 남았습니다.',todayOk:'오늘 조정 목표를 이미 달성했습니다.',incomplete:'ℹ️ 먼저 누락된 지난 날짜를 입력하세요.',modeEconomy:'절약',modeNormal:'일반',modePush:'푸시'},
    hr:{margin:'Rezerva s prilagođenim ciljem',average:'Prilagođeni cilj',daysLeft:'Preostali dani',perDay:'/ dan',ahead:'✅ Imaš prednost: ciljaj oko {avg} dnevno tijekom preostalih {days} dana, {delta} manje dnevno od načina {mode}.',behind:'⚠️ Za tjedni cilj treba oko {avg} dnevno tijekom preostalih {days} dana, {delta} više dnevno od načina {mode}.',steady:'✅ Tempo je dobar: ciljaj oko {avg} dnevno tijekom preostalih {days} dana.',floor:'🛡️ Prednost bi dopustila manje, ali Planner zadržava dnevni minimum od 7,2 M.',todayNeed:'Danas je već zabilježeno {current}; preostaje oko {need} do prilagođenog cilja.',todayOk:'Današnji prilagođeni cilj je već ostvaren.',incomplete:'ℹ️ Najprije dopuni nedostajuće prošle dane.',modeEconomy:'Štednja',modeNormal:'Normalno',modePush:'Pritisak'},
    pt:{margin:'Margem com objetivo ajustado',average:'Objetivo ajustado',daysLeft:'Dias restantes',perDay:'/ dia',ahead:'✅ Estás adiantado: aponta para cerca de {avg} por dia nos {days} dias restantes, {delta} menos por dia do que o modo {mode}.',behind:'⚠️ Para a meta semanal, aponta para cerca de {avg} por dia nos {days} dias restantes, {delta} mais por dia do que o modo {mode}.',steady:'✅ O ritmo está bom: aponta para cerca de {avg} por dia nos {days} dias restantes.',floor:'🛡️ A vantagem permitiria menos, mas o Planner mantém o mínimo diário de 7,2 M.',todayNeed:'Hoje já tens {current} registado; faltam cerca de {need} para o objetivo ajustado.',todayOk:'O objetivo ajustado de hoje já foi atingido.',incomplete:'ℹ️ Completa primeiro os dias anteriores em falta.',modeEconomy:'Economia',modeNormal:'Normal',modePush:'Impulso'}
  };

  function lang(){try{return String(state?.language||'fr').split('-')[0];}catch{return'fr';}}
  function tx(){return T[lang()]||T.en;}
  function tr(k,v={}){let s=tx()[k]||T.en[k]||k;for(const[a,b]of Object.entries(v))s=String(s).replaceAll(`{${a}}`,String(b));return s;}
  function esc(s){return String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]||c));}
  function compact(n){const v=Math.max(0,Number(n)||0);if(v>=1e9)return`${(v/1e9).toFixed(2).replace(/\.00$/,'')} B`;if(v>=1e6)return`${(v/1e6).toFixed(2).replace(/\.00$/,'')} M`;if(v>=1e3)return`${(v/1e3).toFixed(1).replace(/\.0$/,'')} k`;return String(Math.round(v));}
  function signed(n){const v=Number(n)||0;return`${v>=0?'+':'−'}${compact(Math.abs(v))}`;}
  function modeConfig(){let u={mode:'normal',pushTarget:10_000_000};try{u={...u,...JSON.parse(localStorage.getItem(UI_KEY)||'{}')};}catch{}const mode=['economy','normal','push'].includes(u.mode)?u.mode:'normal';const target=mode==='economy'?DAILY_MIN:mode==='push'?Math.max(DAILY_MIN,Number(u.pushTarget)||10_000_000):7_300_000;const name=mode==='economy'?tr('modeEconomy'):mode==='push'?tr('modePush'):tr('modeNormal');return{mode,target,name};}
  function todayId(){try{if(typeof automaticDay==='function')return Math.max(1,Math.min(6,Number(automaticDay())||1));}catch{}const d=new Date().getDay();return d===0?1:Math.max(1,Math.min(6,d));}
  function weekKey(){const d=new Date(),day=d.getDay()||7;d.setHours(12,0,0,0);d.setDate(d.getDate()-day+1);return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
  function history(){try{const h=JSON.parse(localStorage.getItem(HIST_KEY)||'{}');return h.week===weekKey()?h:{week:weekKey(),days:{}};}catch{return{week:weekKey(),days:{}};}}
  function scorePack(){const h=history(),s={},known={};for(let i=1;i<=6;i++){const live=Math.max(0,Number(state?.currentPoints?.[i]||0));if(live>0){s[i]=live;known[i]=true;}else if(Object.prototype.hasOwnProperty.call(h.days||{},String(i))){s[i]=Math.max(0,Number(h.days[i])||0);known[i]=true;}else{s[i]=0;known[i]=false;}}return{s,known};}

  function model(){
    const cfg=modeConfig(),today=todayId(),p=scorePack(),s=p.s,known=p.known,unknownPast=[];
    let past=0;for(let i=1;i<today;i++){if(known[i])past+=s[i];else unknownPast.push(i);}
    const daysLeft=Math.max(1,7-today),weekTarget=cfg.target*6,required=Math.max(0,weekTarget-past);
    const rawAverage=required/daysLeft,average=Math.max(DAILY_MIN,rawAverage),floorActive=rawAverage<DAILY_MIN;
    const current=known[today]?s[today]:0,todayNeed=Math.max(0,average-current);
    let projected=past+Math.max(current,average);for(let i=today+1;i<=6;i++)projected+=average;
    return{cfg,today,s,known,unknownPast,daysLeft,weekTarget,rawAverage,average,floorActive,current,todayNeed,margin:projected-weekTarget,delta:cfg.target-average};
  }

  function style(){if(document.getElementById('gomo-v3192-style'))return;const s=document.createElement('style');s.id='gomo-v3192-style';s.textContent=`.v319-pilot{margin-top:9px;padding:10px;border-radius:14px;background:linear-gradient(145deg,rgba(11,47,68,.92),rgba(7,32,48,.96));border:1px solid rgba(118,203,255,.20)}.v319-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.v319-metric{padding:9px;border-radius:11px;background:rgba(255,255,255,.05)}.v319-metric span{display:block;color:#9fc9dc;font-size:.66rem;font-weight:800}.v319-metric strong{display:block;margin-top:3px;color:#fff;font-size:.95rem}.v319-metric.good strong{color:#9bf0bf}.v319-metric.warn strong{color:#ffd08d}.v319-advice{margin-top:8px;padding:9px 10px;border-radius:11px;background:rgba(55,191,122,.10);color:#a6efc3;font-size:.76rem;font-weight:800;line-height:1.38}.v319-advice.warn{background:rgba(255,173,65,.10);color:#ffd08d}.v319-advice.info{background:rgba(70,165,230,.10);color:#bdeaff}.v319-floor{margin-top:7px;padding:8px 9px;border-radius:10px;background:rgba(70,165,230,.10);color:#bdeaff;font-size:.72rem;font-weight:800;line-height:1.35}.v319-today{margin-top:7px;color:#bdeaff;font-size:.73rem;font-weight:750;line-height:1.35}@media(max-width:580px){.v319-grid{grid-template-columns:1fr}}`;document.head.appendChild(s);}

  function markup(){
    const m=model();if(m.unknownPast.length)return`<div class="v319-pilot"><div class="v319-advice info">${esc(tr('incomplete'))}</div></div>`;
    const d=Math.abs(m.delta),near=d<50_000;let advice,cls='';
    if(near)advice=tr('steady',{avg:compact(m.average),days:m.daysLeft});
    else if(m.delta>0)advice=tr('ahead',{avg:compact(m.average),days:m.daysLeft,delta:compact(d),mode:m.cfg.name});
    else{advice=tr('behind',{avg:compact(m.average),days:m.daysLeft,delta:compact(d),mode:m.cfg.name});cls='warn';}
    const today=m.todayNeed>0?tr('todayNeed',{current:compact(m.current),need:compact(m.todayNeed)}):tr('todayOk');
    const floor=m.floorActive?`<div class="v319-floor">${esc(tr('floor'))}</div>`:'';
    return`<div class="v319-pilot"><div class="v319-grid"><div class="v319-metric ${m.margin>=0?'good':'warn'}"><span>${esc(tr('margin'))}</span><strong>${esc(signed(m.margin))}</strong></div><div class="v319-metric"><span>${esc(tr('average'))}</span><strong>${esc(compact(m.average))}${esc(tr('perDay'))}</strong></div><div class="v319-metric"><span>${esc(tr('daysLeft'))}</span><strong>${m.daysLeft}</strong></div></div><div class="v319-advice ${cls}">${esc(advice)}</div>${floor}<div class="v319-today">${esc(today)}</div></div>`;
  }

  function render(){clearTimeout(timer);style();const week=document.getElementById('gomoV318Week');if(!week||week.hidden)return;const metrics=week.querySelector('.v318-metrics');if(!metrics)return;const box=document.createElement('div');box.innerHTML=markup();const fresh=box.firstElementChild;const old=week.querySelector('.v319-pilot');if(!old)metrics.insertAdjacentElement('afterend',fresh);else if(old.outerHTML!==fresh.outerHTML)old.replaceWith(fresh);const ver=document.getElementById('gomoV240Version');if(ver)ver.textContent=`Version ${VERSION}`;document.querySelectorAll('.v315-version').forEach(n=>n.textContent=`Guide automatique · v${VERSION}`);document.documentElement.setAttribute('data-gomo-v3192-ready','1');}
  function schedule(ms=80){clearTimeout(timer);timer=setTimeout(render,ms);}
  function observeWeek(){if(observer)observer.disconnect();observer=new MutationObserver(list=>{for(const m of list){if(m.target?.closest?.('.v319-pilot'))continue;const inside=m.target?.closest?.('#gomoV318Week');const added=[...m.addedNodes].some(n=>n.nodeType===1&&(n.id==='gomoV318Week'||n.querySelector?.('#gomoV318Week')));if(inside||added){schedule(140);break;}}});observer.observe(document.body,{childList:true,subtree:true});}
  function bind(){document.addEventListener('click',e=>{if(e.target.closest?.('#v315Start,#v315DayOk,[data-go],[data-v316-mode],#v316Apply,#v316Finish,#v316SaveActual,#v316Restart,#v318SaveHistory'))schedule(180);},true);document.addEventListener('change',e=>{if(['v315Day','v315Language','v316PushInput','v317Badges','v317Goal'].includes(e.target?.id))schedule(140);},true);}
  function start(){bind();observeWeek();[0,250,700,1600].forEach(d=>setTimeout(render,d));console.info('GoMo VS Planner weekly adaptive floor',VERSION);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
